### ISSUE TITLE
Update stable version in repo from 1.0.4 to 1.1.1

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.vis-lcars#15]
# Think about update stable version to 1.1.1
**Version**: stable=**1.0.4** (2093 days old) => latest=**1.1.1** (15 days old)
**Installs**: stable=**3123** (93.39%), latest=**216** (6.46%), total=**3344**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L2566)

**Comment by mcm1957** [comment]
A kind reminder.
Is there any reason to delay an update of stable revision?

Feel free to drop a simple note if I should trigger an update.

**Comment by Apollon77** [comment]
go

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 1.1.1 but the current stable version is already 1.1.1.

So this issue should be closed.
