### ISSUE TITLE
Toggle buttons how to set

### ISSUE THREAD

**Issue by marksev1** [ioBroker/ioBroker.vis-lcars#4]
Hello,

how to set toggle button in LCARS? For me it toggles just once then it doesn't toggle back to old value.

See here: 

27. 11. 2016 19:22:398f6ff0dc.00f46
/kitchen/lamp : msg.payload : boolean
true
27. 11. 2016 19:22:408f6ff0dc.00f46
/kitchen/lamp : msg.payload : boolean
false
27. 11. 2016 19:22:428f6ff0dc.00f46
/kitchen/lamp : msg.payload : boolean
false
27. 11. 2016 19:22:468f6ff0dc.00f46
/kitchen/lamp : msg.payload : boolean
false
27. 11. 2016 19:22:478f6ff0dc.00f46
/kitchen/lamp : msg.payload : boolean
false
27. 11. 2016 19:22:478f6ff0dc.00f46
/kitchen/lamp : msg.payload : boolean
false
27. 11. 2016 19:22:488f6ff0dc.00f46
/kitchen/lamp : msg.payload : boolean
false
27. 11. 2016 19:22:488f6ff0dc.00f46
/kitchen/lamp : msg.payload : boolean
false

**Comment by GermanBluefox** [comment]
http://forum.iobroker.net/viewtopic.php?f=12&t=4371#p42563
