### ISSUE TITLE
incorrect button titles

### ISSUE THREAD

**Issue by twonky4** [ioBroker/ioBroker.vis-lcars#6]
There is currently an issue with the titles of the buttons. The (empty) default title is still showing if some title was set.

![image](https://user-images.githubusercontent.com/3495103/30783130-53553036-a13e-11e7-8879-64bf6787b32a.png)

**Comment by GermanBluefox** [comment]
"state" is untertitel. If you clear it, the "(empty) default title" will disappear.

**Comment by twonky4** [comment]
Yeah, you are right. Thanks!

But if I disable the checkbox next to the Untertitel, the "state" appears again.
![image](https://user-images.githubusercontent.com/3495103/30805772-3b8dcfd4-a1f3-11e7-9a5e-e97b8f3366ce.png)

**Comment by twonky4** [comment]
Ah, now I understand the viewing state stuff.
